steps:
  - name: golang
    args:
      - go
      - version
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - get-person
      - --region=australia-southeast1
      - --source=.
      - --trigger-http
      - --runtime=go113
      - --entry-point=GetPerson
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - add-person
      - --region=australia-southeast1
      - --source=.
      - --trigger-http
      - --runtime=go113
      - --entry-point=AddPerson