name: Quality
on: [ pull_request ]

jobs:
  lint:
    runs-on: [ ubuntu ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41
          skip-go-installation: true
        env:
          GOFLAGS: "-mod=vendor"
